### ISSUE TITLE
`babel: command not found`

### ISSUE THREAD

**Issue by fnknzzz** [FrodoLuo/ts-babel-plugin-startkit#1]
Can't start test since babel is not in /node_modules/.bin/ directory

**Comment by FrodoLuo** [comment]
Sorry for responding late.

I added a `@babel/cli` to the devDependencies, please try to install `@babel/cli` and then run test again. [3b25c92](https://github.com/FrodoLuo/ts-babel-plugin-startkit/commit/3b25c9247e4b9b76a0342b179698d272df17b828)
